[package]
name = "cow"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.2.2"
serde = { vsersion="1.0", features=["derive"] }
serde_json="1.0"