[package]
name = "trait_bound"
version = "0.1.0"
authors = ["luojie <xiaoyaojie710@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
